# CI / CD of pr0ton11 builds

name: 'Build'

on:
  push:
    branches:
    - main

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v3
      - name: "Build:dockerlogin"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: "Build:dockerimage"
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64
          tags: ghcr.io/pr0ton11/echo-callback:latest
